# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=1024, null=True)),
                ('channel', models.CharField(max_length=125, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('timing', models.CharField(max_length=125, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
