# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmlist',
            name='detailed',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='filmlist',
            name='original',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='filmlist',
            name='profile',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='filmlist',
            name='thumbnail',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
